server:
  port: 8091

## URL Rest Services applicacion
coins:
  baseURL: 'api'
  healthAPI: '/health-api'
  coinById: "/coins/{idCoin}"
  list: '/coins/list'
  markets: '/coins/markets'
  tickers: '/coins/{idCoin}/tickers'
  history: '/coins/{idCoin}/history'
  marketChart: '/coins/{idCoin}/marketChart'
  rangeById: '/coins/{idCoin}/marketChartRange'
  ohlcById: '/coins/{idCoin}/ohlc'

## Url Coin Gecko RestService
api:
  urlCoinGecko: 'https://api.coingecko.com/api/v3'
  ping: '/ping'
  coin: '/coins/%s'
  coinList: '/coins/list'
  markets: '/coins/markets'
  tickersById: '/coins/%s/tickers'
  historyCoin: '/coins/%s/history'
  marketChartCoin: '/coins/%s/market_chart'
  marketChartRange: '/coins/%s/market_chart/range'
  ohlcById: '/coins/%s/ohlc'
