server:
  port: 8081

## URL Rest Services applicacion
coins:
  baseURL: 'api/coins'
  healthAPI: '/health-api'
  coinList: '/list'
  coinMarket: '/markets'
  coinTickers: '/{idCoin}/tickers'

## Url Coin Gecko RestService
api:
  urlCoinGecko: 'https://api.coingecko.com/api/v3'
  ping: '/ping'
  coin: '/coins'
  coinList: '/coins/list'
  markets: '/coins/markets'
  tickersById: '/coins/%s/tickers'
