server:
  port: 8081

## URL Rest Services applicacion
coins:
  baseURL: 'api/coins'
  healthAPI: '/health-api'
  list: '/list'
  market: '/markets'
  tickers: '/{idCoin}/tickers'
  history: '/{idCoin}/history'
  marketChart: '/{idCoin}/marketChart'
  rangeById: '/{idCoin}/marketChartRange'
  ohlcById: '/{idCoin}/ohlc'

## Url Coin Gecko RestService
api:
  urlCoinGecko: 'https://api.coingecko.com/api/v3'
  ping: '/ping'
  coin: '/coins'
  coinList: '/coins/list'
  markets: '/coins/markets'
  tickersById: '/coins/%s/tickers'
  historyCoin: '/coins/%s/history'
  marketChartCoin: '/coins/%s/market_chart'
  marketChartRange: '/coins/%s/market_chart/range'
  ohlcById: '/coins/%s/ohlc'
